<?php

namespace AppBundle\Repository;

/**
 * sportsDaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sportsDaysRepository extends \Doctrine\ORM\EntityRepository
{
}
