<?php

namespace AppBundle\Repository;

/**
 * sportsInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sportsInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
