<?php

namespace AppBundle\Repository;

/**
 * TrainerInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainerInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
