# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
      AppBundle\Entity\Users: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
       our_db_provider:
                  entity:
                      class: AppBundle:Users
                      property: username
       in_memory:
            memory: ~


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            anonymous: ~
            provider: our_db_provider
            form_login:
                      login_path: login
                      check_path: login
                      username_parameter: _username
                      password_parameter: _password
            logout:
                      path:   /logout
                      target: /

    access_control:
         # require user for /test*
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/userinfo/new, roles: ROLE_USER }

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
