<?php

namespace AppBundle\Repository\Entity;

/**
 * userInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
